### ISSUE TITLE
What is Annottion Value in "'azure.com/tag-selector':"

### ISSUE THREAD

**Issue by JoaoTeixeira-081** [ehrnst/backstage-azure-resource-frontend#7]
So, I have another question, in annotations of my catalog-info.yaml, what its ref/value i should input?
I have all the Secrets of Microsoft {Client_ID/ Client_Secret/ Tenant_ID} well introduce, but I' not getting anything in all tests I have done..
 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/117747993/214826185-13c82783-70cc-46b8-9b53-cca8f74229aa.png">

<img width="859" alt="image" src="https://user-images.githubusercontent.com/117747993/214826829-5f9d7a2b-a33d-4227-908e-12b98fad3b0a.png">

**Comment by ehrnst** [comment]
Hi add it as a [key/value pair](https://github.com/vippsas/backstage-azure-resource-frontend#annotation)

```YAML
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: entity-name
  description: "description"
  annotations:
    azure.com/tag-selector: costCenter/entity-name #this can be anything as long as it matches the tag and value in Azure
```
And remember to add the same tag key and value on your resource group(s) in Azure.
